Repository WordPress/wpcs-docs, pull requests merged in 2022-05, with the labels that each got.

#71 Update html.md
  wordpress-coding-standards/html.md
Labels: Type: Cleanup, Status: Review Ready

#69 Update accessibility.md
  wordpress-coding-standards/accessibility.md
Labels: Type: Cleanup, Status: Review Ready

#68 Update styleguide.md
  styleguide.md
Labels: Type: Cleanup, Status: Review Ready

#72 Update javascript.md
  wordpress-coding-standards/javascript.md
Labels: Type: Cleanup, Status: Review Ready

#73 JS Docs: convert from HTML to markdown
  inline-documentation-standards/javascript.md
Labels: Type: Cleanup, Status: Review Ready

#75 Markdown replace in PHP coding standard
  wordpress-coding-standards/php.md
Labels: enhancement

#77 Use international date format
  wordpress-coding-standards/css.md
Labels: Status: Review Ready

#79 Remove Unused Link
  wordpress-coding-standards/javascript.md
Labels: bug

#70 Update css.md
  wordpress-coding-standards/css.md
Labels: Type: Cleanup, Status: Review Ready

#65 Content update changes in PHP Coding Standards
  wordpress-coding-standards/php.md
Labels: Type: Enhancement, Type: Documentation
